#
# Makefile for the kernel Trustonic drivers
#
TRUSTONIC_ROOT_FOLDER := drivers/trustonic/
# add our modules to kernel.
obj-$(CONFIG_TRUSTONIC_TRUSTED_UI) += mcDrvTui.o

mcDrvTui-objs := t-base-tui/trustedui.o
